stages:
  - build
  - linting

build:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose

test:
  stage: build
  image: rust:latest
  script:
    - cargo test --verbose

linting:
  stage: linting
  image: rust:latest
  before_script:
    - rustup component add clippy
    - cargo install gitlab_clippy
  script:
    - cargo clippy -- -Dwarnings
  after_script:
    - cargo clippy --message-format=json | gitlab-clippy > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
  allow_failure: true

format-check:
  stage: linting
  image: rust:latest
  script:
    - rustup component add rustfmt
    - cargo fmt --check
